#!/usr/bin/env bash

errors_path=~/.dotfiles/errors
exec 2> >(tee -a $errors_path)

cecho() { echo "$(tput setaf ${ci:-1})$1$(tput sgr0)" && ci=$(( (${ci:-1} % 6) + 1 )); }

if [ "$1" = "debian" -o "$1" = "ubuntu" -o "$1" = "mac" ]; then os="$1"; else cecho "Invalid os given\n" && exit 1; fi

if [ "$os" = "debian" -o "$os" = "ubuntu" ]; then
    cecho "Updating package list..."
    sudo apt update

    cecho "Upgrading packages..."
    sudo apt upgrade -y

    if [ "$os" = debian ]; then
        debian_pkgs='curl'
        for pkg in $debian_pkgs; do
            cecho "Installing $pkg..."
            sudo apt install -y $pkg
        done
    fi

    shared_pkgs='zsh tmux cmake ranger vim fd-find ripgrep'
    for pkg in $shared_pkgs; do
        cecho "Installing $pkg..."
        sudo apt install -y $pkg
    done

    cecho "Installing rust..."
    curl https://sh.rustup.rs -sSf | sh -s -- -y

    if [ $? -eq 0 ]; then
        rust_pkgs="exa bat"
        for pkg in $rust_pkgs; do
            cecho "Installing $pkg..."
            ~/.cargo/bin/cargo install exa
        done
    fi

    cecho "Installing fzf..."
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install

elif [ "$os" = "mac" ]; then
    cecho "Installing homebrew..."
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    pkgs="zsh git tmux exa vim sed grep ranger fzf fd bat ripgrep vim"
    for pkg in $pkgs; do
        cecho "Installing $pkg..."
        brew install $pkg
    done

    cecho "Setting up fzf..."
    $(brew --prefix)/opt/fzf/install
fi

cecho "Installing Oh My Zsh..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" "" --unattended

cecho "Installing Oh My Zsh plugins: fast-syntax-highlighting, zsh-autosuggestions..."
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zdharma/fast-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/fast-syntax-highlighting

cecho "Installing improved nano syntax highlighting files..."
git clone https://github.com/scopatz/nanorc.git ~/.nano

cecho "Installing tmux plugin manager..."
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

cecho "Installing tmux-256color terminfo"
curl -LO http://invisible-island.net/datafiles/current/terminfo.src.gz
gunzip terminfo.src.gz
tic -x terminfo.src
rm terminfo.src

cecho "Installing pyenv..."
curl https://pyenv.run | bash

cecho "Backing up and removing old dotfiles..."
[ -f ~/.nanorc ] && cp -iv ~/.nanorc ~/.nanorc.old && rm -v ~/.nanorc;
[ -f ~/.tmux.conf ] && cp -iv ~/.tmux.conf ~/.tmux.conf.old && rm -v ~/.tmux.conf;
[ -f ~/.zshrc ] && cp -iv ~/.zshrc ~/.zshrc.old && rm -v ~/.zshrc;

cecho "Symlinking to new dotfiles..."
ln -isv ~/.dotfiles/nanorc ~/.nanorc
ln -isv ~/.dotfiles/tmux.conf ~/.tmux.conf
ln -isv ~/.dotfiles/zshrc ~/.zshrc
ln -isv ~/.dotfiles/vimrc ~/.vimrc
mkdir -pv ~/.jupyter/custom && ln -isv ~/.dotfiles/jupyter-custom.js ~/.jupyter/custom/custom.js

cecho "Symlinking scripts directory..."
ln -siv ~/.dotfiles/scripts ~/.scripts

cecho "Changing login shell..."
chsh -s $(which zsh)

cecho "$(tput bold)Installation complete. Starting zsh..."
exec zsh
