vim.keymap.set('i', 'jj', '<Esc>')

vim.keymap.set('n', '<C-W><', '<C-W>5<')
vim.keymap.set('n', '<C-W>>', '<C-W>5>')
vim.keymap.set('n', '<C-W>-', '<C-W>5-')
vim.keymap.set('n', '<C-W>+', '<C-W>5+')

vim.keymap.set('n', 'j', [[(v:count > 1 ? "m'" . v:count : "") . 'j']], { expr = true })
vim.keymap.set('n', 'k', [[(v:count > 1 ? "m'" . v:count : "") . 'k']], { expr = true })

vim.keymap.set('n', 'n', 'nzz')
vim.keymap.set('n', 'N', 'Nzz')
vim.keymap.set('n', '[q', '<Cmd>cprevious | normal zz<CR>')
vim.keymap.set('n', ']q', '<Cmd>cnext | normal zz<CR>')
vim.keymap.set('n', '[Q', '<Cmd>cfirst | normal zz<CR>')
vim.keymap.set('n', ']Q', '<Cmd>clast | normal zz<CR>')
vim.keymap.set('n', '[<C-Q>', '<Cmd>cpfile | normal zz<CR>')
vim.keymap.set('n', ']<C-Q>', '<Cmd>cnfile | normal zz<CR>')
vim.keymap.set('n', '[l', '<Cmd>lprevious | normal zz<CR>')
vim.keymap.set('n', ']l', '<Cmd>lnext | normal zz<CR>')
vim.keymap.set('n', '[L', '<Cmd>lfirst | normal zz<CR>')
vim.keymap.set('n', ']L', '<Cmd>llast | normal zz<CR>')
vim.keymap.set('n', '[<C-L>', '<Cmd>lpfile | normal zz<CR>')
vim.keymap.set('n', ']<C-L>', '<Cmd>lnfile | normal zz<CR>')

vim.keymap.set('n', '<leader>re', '<Cmd>mksession! /tmp/session.vim | restart +wqa source /tmp/session.vim<CR>')
