vim.o.autocomplete = true
vim.o.clipboard = 'unnamed'
vim.o.colorcolumn = '+1'
vim.o.complete = '.'
vim.o.completeopt = 'fuzzy,menuone,noinsert,popup'
vim.o.cursorline = true
vim.o.expandtab = true
vim.o.exrc = true
vim.o.ignorecase = true
vim.o.laststatus = 3
vim.o.number = true
vim.o.pumheight = 10
vim.o.relativenumber = true
vim.o.scrolloff = 10
vim.o.shada = "'500"
vim.o.shiftwidth = 4
vim.cmd('set shortmess+=c')
vim.o.signcolumn = 'yes:2'
vim.o.smartcase = true
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.swapfile = false
vim.o.tabstop = 4
vim.o.updatetime = 100

vim.g.mapleader = ' '
