#!/usr/bin/env bash

# Run an ahk file given a wslpath. Set the AutohotKey.exe path with env var
# WINDOWS_AHK_PATH (defaults to C:\Program Files\AutoHotkey\AutoHotkey.exe)

if [ -z "$1" ]; then
    echo No file given.
    exit 1
fi

windows_ahk_path="${WINDOWS_AHK_PATH:-C:\\Program Files\\AutoHotkey\\AutoHotkey.exe}"
wsl_ahk_path=$(wslpath "$windows_ahk_path")

windows_file_path=$(wslpath -w "$1")

"$wsl_ahk_path" "$windows_file_path"
