#!/usr/bin/env bash

set -euo pipefail

# osx
# Returns if we're running on osx
osx() {
    [ "$(uname)" = "Darwin" ]
}

# linux
# Returns if we're running on linux
linux() {
    [ "$(uname)" = "Linux" ]
}

# clone_or_pull <repository> <directory>
# Clones a repository into a directory if it doesn't exist, otherwise pulls in the latest changes.
clone_or_pull() {
    if [ ! -d "$2" ]; then
        git clone --depth 1 "$1" "$2"
    else
        git -C "$2" pull
    fi
}

# cecho <message>
# Displays a line of text in a different colour each time its called.
cecho() {
    echo "$(tput setaf "${ci:-1}")$1$(tput sgr0)" && ci=$(( (${ci:-1} % 6) + 1 ))
}

shared_pkgs=(
    bat
    cmake # nvim build dep
    curl
    eza
    gettext # nvim build dep
    git
    ripgrep
    stow
    tmux
    zsh
)

brew_pkgs=(
    coreutils # provides gdircolors
    fd
    fzf
    git-delta
    ninja # nvim build dep
    "${shared_pkgs[@]}"
)

apt_pkgs=(
    build-essential
    fd-find
    fzf
    ninja-build    # nvim build dep
    "${shared_pkgs[@]}"
)

linux_cargo_pkgs=(
    git-delta
)

cecho "Installing rust"
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path

cecho "Sourcing ~/.cargo/env"
# shellcheck disable=SC1090
source ~/.cargo/env

if osx; then
    cecho "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    cecho "Updating list of available packages"
    brew update

    cecho "Installing ${brew_pkgs[*]}"
    brew install "${brew_pkgs[@]}"
fi

if linux; then
    cecho "Updating list of available packages"
    sudo apt update

    cecho "Installing ${apt_pkgs[*]}"
    sudo apt install -y "${apt_pkgs[@]}"

    cecho "Installing ${linux_cargo_pkgs[*]}"
    cargo install "${linux_cargo_pkgs[@]}"
fi

if linux; then
    cecho "Linking fd to fdfind"
    sudo ln -sfv "$(which fdfind)" /usr/local/bin/fd

    cecho "Linking bat to batcat"
    sudo ln -sfv "$(which batcat)" /usr/local/bin/bat
fi

cecho "Installing ZSH plugins: zsh-syntax-highlighting, zsh-autosuggestions, zsh-completions"
clone_or_pull https://github.com/zsh-users/zsh-autosuggestions ~/.local/share/zsh/plugins/zsh-autosuggestions
clone_or_pull https://github.com/zsh-users/zsh-syntax-highlighting ~/.local/share/zsh/plugins/zsh-syntax-highlighting
clone_or_pull https://github.com/zsh-users/zsh-completions.git ~/.local/share/zsh/plugins/zsh-completions

cecho "Installing tmux plugin manager"
clone_or_pull https://github.com/tmux-plugins/tpm ~/.local/share/tmux/plugins/tpm

cecho "Installing nvm"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

cecho "Installing pyenv"
if [ ! -d ~/.pyenv ]; then
    curl https://pyenv.run | bash
else
    ~/.pyenv/bin/pyenv update
fi

cecho "Installing nvim"
mkdir -p ~/scratch
clone_or_pull https://github.com/neovim/neovim ~/scratch/neovim
make -C ~/scratch/neovim CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make -C ~/scratch/neovim install

cecho "Installing Nord theme dircolors"
curl --output ~/.dir_colors https://raw.githubusercontent.com/nordtheme/dircolors/refs/heads/develop/src/dir_colors

cecho "Moving .zshrc -> .zshrc.old"
mv -iv ~/.zshrc ~/.zshrc.old

cecho "Symlinking config files"
~/.dotfiles/scripts/symlink_config_files

cecho "Updating bat theme cache"
bat cache --build

cecho "Installation complete. Starting zsh"
exec zsh
