vim.cmd 'augroup commentary'
vim.cmd '  autocmd FileType sql setlocal commentstring=--%s'
vim.cmd '  autocmd FileType toml setlocal commentstring=#%s'
vim.cmd '  autocmd FileType please setlocal commentstring=#%s'
vim.cmd 'augroup END'
