-- require all of these in a callback so that we can hot reload them
vim.keymap.set('n', '<leader>pb', function()
  require('please').build()
end, { desc = 'please.build()' })
vim.keymap.set('n', '<leader>pr', function()
  require('please').run()
end, { desc = 'please.run()' })
vim.keymap.set('n', '<leader>pt', function()
  require('please').test()
end, { desc = 'please.test()' })
vim.keymap.set('n', '<leader>pct', function()
  require('please').test({ under_cursor = true })
end, { desc = 'please.test({ under_cursor = true })' })
vim.keymap.set('n', '<leader>pd', function()
  require('please').debug()
end, { desc = 'please.debug()' })
vim.keymap.set('n', '<leader>pcd', function()
  require('please').debug({ under_cursor = true })
end, { desc = 'please.debug({ under_cursor = true })' })
vim.keymap.set('n', '<leader>ph', function()
  require('please').history()
end, { desc = 'please.history()' })
vim.keymap.set('n', '<leader>pch', function()
  require('please').clear_history()
end, { desc = 'please.history()' })
vim.keymap.set('n', '<leader>pp', function()
  require('please').set_profile()
end, { desc = 'please.set_profile()' })
vim.keymap.set('n', '<leader>pm', function()
  require('please').maximise_popup()
end, { desc = 'please.maximise_popup()' })
vim.keymap.set('n', '<leader>pj', function()
  require('please').jump_to_target()
end, { desc = 'please.jump_to_target()' })
vim.keymap.set('n', '<leader>py', function()
  require('please').yank()
end, { desc = 'please.yank()' })
vim.keymap.set('n', '<leader>pl', function()
  require('please.plugin').reload()
end, { desc = 'please.plugin.reload()' })
