-- require all of these in a callback so that we can hot reload them
vim.keymap.set('n', '<Leader>pb', function()
  require('please').build()
end, { desc = 'please.build()' })
vim.keymap.set('n', '<Leader>pr', function()
  require('please').run()
end, { desc = 'please.run()' })
vim.keymap.set('n', '<Leader>pt', function()
  require('please').test()
end, { desc = 'please.test()' })
vim.keymap.set('n', '<Leader>pct', function()
  require('please').test({ under_cursor = true })
end, { desc = 'please.test({ under_cursor = true })' })
vim.keymap.set('n', '<Leader>pd', function()
  require('please').debug()
end, { desc = 'please.debug()' })
vim.keymap.set('n', '<Leader>pcd', function()
  require('please').debug({ under_cursor = true })
end, { desc = 'please.debug({ under_cursor = true })' })
vim.keymap.set('n', '<Leader>ph', function()
  require('please').history()
end, { desc = 'please.history()' })
vim.keymap.set('n', '<Leader>pch', function()
  require('please').clear_history()
end, { desc = 'please.history()' })
vim.keymap.set('n', '<Leader>pp', function()
  require('please').set_profile()
end, { desc = 'please.set_profile()' })
vim.keymap.set('n', '<Leader>pm', function()
  require('please').maximise_popup()
end, { desc = 'please.maximise_popup()' })
vim.keymap.set('n', '<Leader>pj', function()
  require('please').jump_to_target()
end, { desc = 'please.jump_to_target()' })
vim.keymap.set('n', '<Leader>py', function()
  require('please').yank()
end, { desc = 'please.yank()' })
